language: node_js
node_js: '14'
sudo: false

cache: npm

jobs:
  include:
    - stage: Lint
      script: npm run lint
    - stage: Test
      script: npm run test -- --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
